// src/components/4chan/board-post.component.ts
import { Component, Input } from "@angular/core";

@Component({
    selector: "board-post",
    template: `
        <img src="{{ thread.imgsrc }}">
        <div class="thread-count">
            R: <b>{{ thread.replyCount }}</b>
            I: <b>{{ thread.imgCount }}</b>
        </div>
        <div class="thread-op">
            <b  class="title"
                [innerHTML]="thread.subtitle"
            ></b>
            <div
                [innerHTML]="thread.com"
            ></div>
        </div>
    `
})
export class BoardPostComponent {
    @Input() thread = {};
}

// client/components/BoardPost/BoardPost.jsx
import React from 'react';
import Tooltip from '../Tooltip';

export default ({ post, fetchThread }) => {
    const {id, title, comment, date, imgsrc, replies} = post;

    return (
        <div 
            className="board-post"
            onClick={() => fetchThread(id)}
        >
            <img src={imgsrc.sm} />
            <Tooltip>
                <div className="count">
                    R: <b>{replies.textCount}</b> |
                    I: <b>{replies.imgCount}</b>
                </div>
            </Tooltip>
            <div className="op">
                <b dangerouslySetInnerHTML={{__html: title}} className="title"></b>
                <div dangerouslySetInnerHTML={{__html: comment}}></div>
            </div>
        </div>
    )
}
