// src/components/4chan/board-post.component.ts
import { Component, Input } from "@angular/core";

@Component({
    selector: "board-post",
    template: `
        <img src="{{ thread.imgsrc }}">
        <div class="thread-count">
            R: <b>{{ thread.replyCount }}</b>
            I: <b>{{ thread.imgCount }}</b>
        </div>
        <div class="thread-op">
            <b  class="title"
                [innerHTML]="thread.subtitle"
            ></b>
            <div
                [innerHTML]="thread.com"
            ></div>
        </div>
    `
})
export class BoardPostComponent {
    @Input() thread = {};
}

// client/components/BoardPost.jsx
import React from 'react';
import { connect } from 'react-redux';
import { bindActionCreators } from 'redux';

export default function({post, fetchThread}) {        
    const {id, title, comment, date, imgsrc, replies} = post;

    return (
        <div className="post"
             onClick={() => fetchThread(id)}>
            <img src={imgsrc.sm} />
            <div className="thread-count">
                R: <b>{replies.textCount}</b> |
                I: <b>{replies.imgCount}</b>
            </div>
            <div className="thread-op">
                <b dangerouslySetInnerHTML={{__html: title}} className="title"></b>
                <div dangerouslySetInnerHTML={{__html: comment}}></div>
            </div>
        </div>
    )
}
