// src/components/4chan/board-post.component.ts
import { Component, Input } from "@angular/core";

@Component({
    selector: "board-post",
    template: `
        <img src="{{ thread.imgsrc }}">
        <div class="thread-count">
            R: <b>{{ thread.replyCount }}</b>
            I: <b>{{ thread.imgCount }}</b>
        </div>
        <div class="thread-op">
            <b  class="title"
                [innerHTML]="thread.subtitle"
            ></b>
            <div
                [innerHTML]="thread.com"
            ></div>
        </div>
    `
})
export class BoardPostComponent {
    @Input() thread = {};
}

// src/client/components/BoardPost/BoardPost.jsx
import React from 'react';
import Tooltip from '../Tooltip';

export default ({ post, fetchThread }) => {
    const {id, title, comment, date, imgsrc, replies} = post;
    return (
        <div 
            id={"t"+id}
            className="board-post"
            onClick={() => fetchThread(id)}
        >
            <img src={imgsrc.sm} />
            <Tooltip>
                <div className="count">
                    <span>
                        <span>
                            <i className="mdi mdi-comment-text"></i>
                            <b>{replies.textCount}</b>
                        </span>
                        <span className="updater updater-replycount">
                            +1
                        </span>
                    </span>
                    <span>
                        <span>
                            <i className="mdi mdi-message-image"></i>
                            <b>{replies.imgCount}</b>
                        </span>
                        <span className="updater updater-imgcount">
                            +1
                        </span>
                    </span>
                </div>
            </Tooltip>
            <div className="op">
                <b dangerouslySetInnerHTML={{__html: title}} className="title" />
                <div dangerouslySetInnerHTML={{__html: comment}} />
            </div>
        </div>
    )
}
